### ISSUE TITLE
Support Bootstrap's look-and-feel?

### ISSUE THREAD

**Issue by chuanconggao** [LeaVerou/awesomplete#13387]
I am using this plugin with Bootstrap. It would be great to support Bootstrap's look-and-feel. Currently I am customizing it myself via CSS, but it is very tedious.

**Comment by LeaVerou** [comment]
I would expect its style is pretty generic that it would go well with Bootstrap. What exactly do you need customized?

**Comment by chuanconggao** [comment]
More specifically, the colors, the pointer size, the font size, the distance between the suggestion and the input, etc. I am currently using the CSS of Bootstrap's popover component, to get a consist look-and-feel.

**Comment by LeaVerou** [comment]
I think this means we need better documentation in the CSS file (or the website). The CSS is easy to customize, but I can see how it could be tedious for someone unfamiliar with the code…

**Comment by owlmsj** [comment]
agreed with @chuanconggao. Lib is great, but a bootstrap css plugin would be nice to easily integrates to bootstrap projects.

**Comment by edwinlunando** [comment]
Yes, I am waiting for this too. :)

**Comment by MaPePeR** [comment]
All i had to do was 

``` css
div.awesomplete {
    display: block;
}
```

to make it working with bootstrap. (I'm not an expert on CSS or web development, so i'm probably not aware of the full consequences of this - but it did allow me to use awesomplete with bootstrap)

**Comment by rwilson** [comment]
Here's a tweak to allow awesomplete to play well with bootstrap form groups. By defualt, an awesomplete on an input in a form group will render behind the input, because the input is floated and set to z-index 2.

``` css
/**
 * bootstrap's input groups modify the float & z-index of form-controls, this allows awesomplete
 * to assume the position of the form-control and reset the input
 */
.input-group div.awesomplete {
    position: relative;
    z-index: 2;
    float: left;
    width: 100%;
    margin-bottom: 0;
}
.input-group div.awesomplete > input {
    float: none;
}
.input-group div.awesomplete > ul {
    z-index: 3; /* bootstrap sets .input-group .form-control to 2 */
}
```

**Comment by rwilson** [comment]
Additional CSS to correct the border-radius for Bootstrap form controls nested within awesomplete, since Bootstrap's CSS does not account for a level between `.input-group` and `.form-control`.

``` css
/* reinstitute initial .form-control border radius when nested within .awesomeplete */
.input-group .awesomplete .form-control {
    border-radius: 4px;
}
/* reinstitute .border-radius squaring within form groups */
.input-group .awesomplete:first-child .form-control {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
.input-group .awesomplete:not(:first-child) .form-control {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}
.input-group .awesomplete:not(:first-child):not(:last-child) .form-control {
    border-radius: 0;
}
```
