### ISSUE TITLE
Can I show the suggestion without <mark>?

### ISSUE THREAD

**Issue by nodocaengine** [LeaVerou/awesomplete#16939]
When inputting a word in the awesomplete form, there is the suggestion <ul> and <li>s they are marked matching letters with inputting.
It looks always good, but now I don't want to mark letters in <li>s.
Can I show <li>s without <mark>?

**Comment by LeaVerou** [comment]
CSS should work:

``` css
div.awesomplete mark { background: transparent }
```
