### ISSUE TITLE
Animation Settings?

### ISSUE THREAD

**Issue by barbedCoil** [LeaVerou/awesomplete#17052]
Great component - it's exactly what I have been looking for.

However, my clients hate animation - is there a way to turn off animation?  

No problem if not just thought worth asking

Thanks!

**Comment by LeaVerou** [comment]
The animation is done with CSS, so you can just override it:

```css
.awesomplete > ul {
    transition: none;
}
```
