### ISSUE TITLE
Autocomplete disappear under other elements, fix z-index?

### ISSUE THREAD

**Issue by lorenzomorandini** [LeaVerou/awesomplete#17120]
I'm using awesomplete in django-admin but the pop-up disappears under other elements of the page. Is there a make to make sure it's always on top?

**Comment by LeaVerou** [comment]
```css
.awesomplete > ul {
	z-index: 2; /* increase until the problem is fixed */
}
```
