### ISSUE TITLE
Awesomeplete interferes with Bootstrap form-group styling

### ISSUE THREAD

**Issue by eaglebush** [LeaVerou/awesomplete#17225]
Hi,

My bootstrap form group default style is like this:

![image](https://user-images.githubusercontent.com/32386756/92419786-266e9a00-f1a2-11ea-93d5-cbc5ae82902b.png)

With Awesomeplete applied, it becomes this:

![image](https://user-images.githubusercontent.com/32386756/92419810-4aca7680-f1a2-11ea-8c76-1940502392e4.png)

Is there a workaround with this?

Thanks for being Awesome!

**Comment by goulvench** [comment]
Hi @eaglebush, and anyone having the same issue. You need to override display for the `awesomplete` div which wraps the input. `.form-group` is in Bootstrap 4 but the following should work just the same (using Bootstrap 5):

```css
/* Override awesomplete default style to match Bootstrap's block inputs */
.awesomplete {
  display: block;
}
```

```html
<label for="input_id">Input label text</label>
<input type="text" class="form-control awesomplete" id="input_id" data-list="Ada, Java, JavaScript, Brainfuck, LOLCODE, Node.js, Ruby on Rails" />
```

Here's a codepen to see it live: https://codepen.io/goulvench/pen/VwpOXeE
